version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: dev_jimmodel_postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  minio:
    image: quay.io/minio/minio
    container_name: jimmodel_minio
    restart: always
    # volumes:
    #   - ${MINIO_DATA:-minio_data}:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      retries: 1
      start_period: 5s
      timeout: 5s
  minio-mc:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./scripts/minio-entrypoint.sh:/scripts/entrypoint.sh
    entrypoint: /scripts/entrypoint.sh
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      ACCESS_KEY: ${S3_ACCESS_KEY}
      SECRET_KEY: ${S3_SECRET_KEY}
      BUCKET_NAME: ${S3_BUCKET_NAME}
    labels:
      - "traefik.enable=false"
