version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: dev_jimmodel_postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
