version: "3.9"

services:
  reverse-proxy:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.postgres.address=:5432/tcp"
    ports:
      - "80:80"
      - "8080:8080"
      - "5432:5432"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:16-alpine
    container_name: jimmodel_postgres
    restart: always
    volumes:
      - ${DB_DATA_PATH:-postgres_data}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.jimmodel-db.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.jimmodel-db.entrypoints=postgres"
      - "traefik.tcp.services.jimmodel-db.loadbalancer.server.port=5432"

  minio: 
    image: quay.io/minio/minio
    container_name: jimmodel_minio
    restart: always
    volumes:
      - ${MINIO_DATA:-minio_data}:/data 
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jimmodel-minio.rule=Host(`minio.jimmodel.com`)"
      - "traefik.http.routers.jimmodel-minio.entrypoints=web"
      - "traefik.http.services.jimmodel-minio.loadbalancer.server.port=9001"
    
  app:
    build:
      context: .
      args:
        - NODE_ENV=production
    container_name: jimmodel_app
    restart: always
    volumes:
      - ${FILE_STORAGE_PATH:-postgres_data}:/app/file_storage
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jimmodel-app.rule=Host(`web.jimmodel.com`)"
      - "traefik.http.routers.jimmodel-app.entrypoints=web"
      - "traefik.http.services.jimmodel-app.loadbalancer.server.port=3000"

volumes:
  postgres_data:
  minio_data:
