name: Build

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Build

    env: 
      IMAGE_NAME: putto2002/jimmodel_app

    steps:
    - uses: actions/checkout@v3
  
    - name: Build Docker Image
      run: docker build . --tag ${{env.IMAGE_NAME}}:lastest --tag ${{env.IMAGE_NAME}}:${{github.sha}} --platform linux/arm64

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker Image
      run: docker push ${{env.IMAGE_NAME}}:lastest
   
